server:
  port: 10001

spring:
  application:
    name: camunda-platform
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://host:port/database?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: xxxx
    password: xxxx
    type: com.alibaba.druid.pool.DruidDataSource

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: mysql
    filter:
      create: All tasks
    auto-deployment-enabled: false